name: Test
on:
  push

jobs:
  test-pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Tools
        uses: ./.github/actions/setup-tools

      - name: Setup NPM Packages
        uses: ./.github/actions/setup-yarn

      - name: Run unit tests
        run: yarn test

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Rerun Pre-Commit Hooks on CI
        run: |
          pip install -r requirements.txt
          pre-commit run --all-files

  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
